spring:
  resources:
    add-mappings: true
    cache:
      cachecontrol:
        max-age: 3600
    chain:
      cache: true
      # 启用资源链
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#    password:
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      # 测试链接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        # 最大链接数，默认8
        max-active: 8
        # 最大链接阻塞等待时间
        max-wait: 10000ms
        # 最大空闲链接
        max-idle: 200
        min-idle: 5
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.naichuan.seckill.pojo
# Mybatis SQL打印（方法接口所在的包，不是mapper.xml所在的包）
logging:
  level:
    com.naichuan.seckill.mapper: debug
server:
  port: 8111
